name: Remote Deploy

on:
  push:
    branches:
      - main  # Скрипт сработает, когда ты сделаешь push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu для выполнения задачи
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m  # Увеличиваем до 30 минут
          script: |
            cd /var/www/my-pwa
            git pull origin main # 1. Останавливаем контейнеры и удаляем их, чтобы освободить порты
            sudo docker-compose down # 2. Собираем и запускаем заново
            sudo docker-compose up --build -d # 3. Чистим мусор (старые образы), чтобы диск не переполнился
            sudo docker image prune -f