name: Remote Deploy

on:
  push:
    branches:
      - main  # Скрипт сработает, когда ты сделаешь push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu для выполнения задачи
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/my-pwa
            git pull origin main
            # Используем новую команду docker compose (она лучше понимает compose.yaml)
            sudo docker compose down
            sudo docker compose up --build -d
            sudo docker image prune -f